name: Fedora

on: [pull_request]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          dnf install -y readline-devel coreutils make gcc python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install norminette

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Norminette
        run: |
          python3 -m norminette . > norm.log || true
          if grep "Error:" norm.log | grep -v -E "Global variable|WRONG_SCOPE_VAR" > filtered_errors.log; then
            echo "❌ Norminette Errors Found:"
            cat filtered_errors.log
            exit 1
          else
            echo "✅ Norminette Success"
          fi
      
      - name: Compilation
        run: |
          make
          make clean
          make fclean
          make re

      - name: Basic tests
        run: |
          gtimeout 2s ./minishell < /dev/null
          echo "ls -la" | gtimeout 2s ./minishell
          echo "/bin/ls" | gtimeout 2s ./minishell
          echo "env" | gtimeout 2s ./minishell
          echo "ls | cat -e" | gtimeout 2s ./minishell