name: Ubuntu

on: [pull_request]

jobs:
  check-quality:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libreadline-dev

      - name: Install Norminette
        run: |
          python3 -m pip install --upgrade pip
          pip install norminette

      - name: Norminette
        run: |
          norminette . > norm.log || true
          cat norm.log

          if grep "Error:" norm.log | grep -v -E "Global variable|WRONG_SCOPE_VAR" > filtered_errors.log; then
            echo "❌ Norminette Errors Found:"
            cat filtered_errors.log
            exit 1
          else
            echo "✅ Norminette Success"
          fi
      
      - name: Compilation
        run: |
          make
          make clean
          make fclean
          make re